export const dummyArray = [
  { item: '1', key: '1', class: 'yellow' },
  { item: '2', key: '2', class: 'yellow' },
  { item: '3', key: '3', class: 'yellow' },
  { item: '4', key: '4', class: 'yellow' },
  { item: '5', key: '5', class: 'yellow' },
  { item: '6', key: '6', class: 'yellow' },
  { item: '7', key: '7', class: 'yellow' },
  { item: '8', key: '8', class: 'yellow' },
  { item: '9', key: '9', class: 'yellow' },
  { item: '10', key: '10', class: 'yellow' },
  { item: '11', key: '11', class: 'yellow' },
  { item: '12', key: '12', class: 'yellow' },
  { item: '13', key: '13', class: 'yellow' },
  { item: '14', key: '14', class: 'yellow' },
  { item: '15', key: '15', class: 'yellow' },
  { item: '16', key: '16', class: 'yellow' },
  { item: '17', key: '17', class: 'yellow' },
  { item: '18', key: '18', class: 'yellow' },
  { item: '19', key: '19', class: 'yellow' },
  { item: '20', key: '20', class: 'yellow' },
  { item: '21', key: '21', class: 'yellow' },
  { item: '22', key: '22', class: 'yellow' },
  { item: '23', key: '23', class: 'yellow' },
  { item: '24', key: '24', class: 'yellow' }
]
